In [1]:
#라이브러리 로딩하기
import numpy as np

### ndarray 생성하기(1차원)

In [2]:
list1 = [1,2,3,4,5]
list1

[1, 2, 3, 4, 5]

In [3]:
# 앞쪽에 array 하고 소괄호 안쪽에 데이터가 들어가 있는 형태를 numpy 배열 이라고 한다.
arr1 = np.array(list1)
arr1

array([1, 2, 3, 4, 5])

### ndarray 생성하기(2차원)

In [4]:
#가로축 -> 행, 세로축 -> 열
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
#3차원 
arr3 = np.array([[[1,2,3],[4,5,6]] , [[7,8,9],[10,11,12]]])
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

### ndarray 객체의 속성을 활용해서 자료구조 파악하기!
- 배열의 크기 확인하기 : shape

In [6]:
#배열명.shape 
print(arr1.shape) # 1차원은 -> 데이터의 개수 
print(arr2.shape) # 2차원은 -> (행,열) 

(5,)
(2, 3)


- 배열의 요소개수 확인하기 : size

In [7]:
print(arr1.size)
print(arr2.size)

5
6


- 배열의 차원 확인하기 : ndim

In [8]:
# 배열명.ndim
print(arr1.ndim)
print(arr2.ndim)

1
2


- 배열의 타입 확인하기 : dtype

In [9]:
print(arr1.dtype)
print(arr2.dtype)

int32
int32


In [10]:
print(f'배열의 크기 : {arr3.shape}\n') 
print(f'배열의 차원 : {arr3.ndim}') 
print(f'배열의 개수 : {arr3.size}')

배열의 크기 : (2, 2, 3)

배열의 차원 : 3
배열의 개수 : 12


### 특정한 값으로 배열 생성하기
- 배열 안에 있는 값들을 특정한 값으로 초기화 하면서 생성하기

In [11]:
#배열의 값을 0으로 초기화하면서 생성하기 # 튜플형식으로 적어야함 (())
arr_zero=np.zeros((2,3)) # 2차원배열 생성시 (행,열)
arr_zero

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
# 데이터를 하나만 넣으면? 1차원 배열의 개수이다
np.zeros(3)

array([0., 0., 0.])

In [13]:
# 배열안의 모든값들을 1로 초기화하면서 생성하기
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
# 배열안의 모든 값들을 내가 원하는 값으로 초기화하면서 생성하기
# np.full((행,열),내가원하는 값)
np.full((2,3),7)

array([[7, 7, 7],
       [7, 7, 7]])

- 1부터 50까지 숫자데이터를 가지고 있는 1차원 arr4 생성

In [15]:
list2=[]
for i in range(1,51) :
    list2.append(i)
    
arr4 = np.array(list2)
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [16]:
# arange(시작값, 끝값+1, 증감값)
arr5 = np.arange(1,51,1)
arr5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [17]:
#1부터 50까지 4씩 증가하는 arr6생성
arr6 = np.arange(1,51,4)
arr6

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49])

- 랜덤값 집어넣어서 배열 생성하기

In [18]:
# np.random.randint(시작값, 끝값+1, size = 배열의 크기)
arr_ran=np.random.randint(2,10, size = (2,3))
arr_ran

array([[7, 7, 3],
       [7, 9, 9]])

In [19]:
#size를 적어주지 않을 경우에는? -> 1차원 배열이 생성된다.
np.random.randint(2,10)

4

- 배열의 타입을 지정하면서 배열 생성하기!

- 배열의 타입 변경하기
    - 배열명.astype(타입)

In [20]:
# 내가 원하는 배열의 타입으로 지정해서 생성!
arr_type=np.array([1.1,2.2], dtype=np.int64)
arr_type

array([1, 2], dtype=int64)

In [21]:
# 배열의 타입 변경하기
arr_type.astype('float64')

array([1., 2.])

 ### Array 연산
 - numpy는 기본적으로 array 간의 연산을 지원해준다 ( 요소별 연산 )
 - 행과 열이 같은 위치값이 연산이 된다 ex) [1,2,3] + [4,5,6] = [5,7,9]

In [22]:
arr_a = np.array([1,2,3])
arr_a

array([1, 2, 3])

In [23]:
arr_b = np.array([4,5,6])
arr_b

array([4, 5, 6])

In [24]:
arr_a+arr_b

array([5, 7, 9])

In [25]:
arr_a*arr_b

array([ 4, 10, 18])

In [26]:
arr_c = np.array([1,2,3,4,5])
arr_c

array([1, 2, 3, 4, 5])

In [27]:
# 덧셈과 뺼셈에서는 기본적으로 두행렬의 크기가 같아야 한다!
arr_a+arr_c #<- 오류

ValueError: operands could not be broadcast together with shapes (3,) (5,) 

In [ ]:
#2차원 배열 연산
arr2_a=np.array([[1,2,3],[4,5,6]]) # <- 2차원은 대괄호 2개

arr2_b=np.array([[7,8,9],[10,11,12]])

In [ ]:
arr2_a+arr2_b

In [ ]:
#배열+ 숫자 = ?
arr2_a+5 #<- 각 요소에 5를 더해지게 됨

In [ ]:
arr2_b*2 #<- 각 요소에 2를 곱해지게 됨

 ### 인덱싱, 슬라이싱
 - 인덱싱 : 하나의 결과값을 가져오고 싶을 때 사용
 - 슬라이싱 : 여러개의 결과값을 가져오고 싶을 때 사용

##### 인덱싱

In [ ]:
# 1차원 배열 인덱싱
arr_1 = np.array([0,1,2,3,4,5,6])
arr_1

In [ ]:
# 숫자 2 인덱싱
arr_1[2]

In [ ]:
# 2차원 배열 인덱싱하기!
arr_2 = np.array([[1,2,3],[4,5,6]])
arr_2

In [ ]:
# 0행 가져오기 -> 2차원 배열에서 하나만 적어주면 행 인덱싱
arr_2[0]

In [ ]:
# 숫자 2 가져오기
arr_2[0][1]

In [ ]:
# 0행 1열 가져오는 또 다른 방법! # 이 방법은 np.array([][]) 방식으로 만들어야 되는 기능임
arr_2[0,1]
# 컴마를 기준으로 앞이 행 뒤가 열을 의미한다!

In [ ]:
list_3 = [[1,2,3,4,5,6], 
          [7,7,8,9,10,11,12]] 
# <- 이건 numpy 배열이 아님 그냥 리스트임
arr_3=[[1,2,3,4,5,6], 
          [7,7,8,9,10,11,12]] 

list_3 = np.array([[1,2,3,4,5,6], 
          [7,7,8,9,10,11,12]])
list_3

In [ ]:
# 숫자 9 가져오기
arr_3[1][3]


### 슬라이싱

In [ ]:
# 0부터 9까지 1씩 증가하는 1차원 배열 생성
arr_4 = np.arange(0,10,1)
arr_4

In [ ]:
# 2번 ~ 5번까지 슬라이싱
# 배열명[시작:끝+1]
arr_4[2:6]

In [ ]:
#특정 인덱스 부터 끝까지 가져오고 싶을 때 ! [ 시작인덱스 : ]
#3부터 끝까지
arr_4[3:]

In [ ]:
# 처음부터 특정인덱스까지 가져오고 싶을 때? [ : 끝 인덱스 ]
arr_4[:5]

In [ ]:
# 전체 데이터 가져오고 싶을 때는?
arr_4[:]

In [ ]:
arr_4

In [ ]:
# 슬라이싱한 곳에 한번에 데이터 넣기!
arr_4[2:5] = 7

In [ ]:
arr_4

In [ ]:
## 1부터 50까지 1차원 배열 생성하기 
# 배열명.reshape(행,열) -> 배열의 크기를 재배열
arr_5 = np.arange(1,51,1).reshape(5,10)
arr_5

In [ ]:
# 정확하게 모를 때는 -1 적어주기!
arr_5 = np.arange(1,51,1).reshape(5,-1)
arr_5

In [ ]:
# 2행 15 16 17 만 가져오는 슬라이싱기법
arr_5[1][4:7]
# arr_5[1,4:7] <- 이 방법도 됨

In [ ]:
arr_5[1,4:7]

In [ ]:
# 전체행의 0열만 출력해오기!
arr_5[:,0] # arr_5[:] < - 전체 행 // arr_5[,0] <- 1열

In [ ]:
arr_5

In [ ]:
# 3행의 전체열 출력 arr_5[행 , 열]
arr_5[3,:]

In [ ]:
arr_5

In [ ]:
# 전체 행의 0렬부터 2열까지 출력
arr_5[:,:3]

In [ ]:
# 22,33 만 가져오기 == [[행,행][열,열]]
arr_5[[2,3],[1,2]]

In [ ]:
# 11 22 33 = [[행,행,행],[열,열,열]]
arr_5[[1,2,3],[0,1,2]]

### BMI 계산 실습

In [ ]:
# txt 파일 불러오는 방법
data = np.loadtxt('height_weight(p).txt', delimiter = ',') 
# delimiter -> 데이터가 어떤 기호로 구분되어 있는 지 알려주는 속성

In [ ]:
data.shape # shape= 몇행 몇열인지 알려주는 함수

In [ ]:
data

In [ ]:
# BMI 지수 = 몸무게(kg) / 키(m)*키(m)

# 1. 키데이터 가져오기 - m 변수에 담아주기

# 2. 몸무게 데이터 가져오기 - kg 변수에 담아주기

# 3. 키 데이터 변환 (키 *0.01)

# 4. 몸무게 데이터 변환 (몸무게/2.204) : 파운드 -> kg

# 5. BMI 지수 구해주기

In [ ]:
# 1. 키데이터 가져오기 - m 변수에 담아주기
m=data[0]
m

In [ ]:
# 2. 몸무게 데이터 가져오기 - kg 변수에 담아주기
kg=data[1]
kg

In [ ]:
# 3. 키 데이터 변환
m = m*0.01

In [ ]:
# 4. 몸무게 데이터 변환 (몸무게/2.204) : 파운드 -> kg
kg = kg/2.204

In [ ]:
# 5. BMI 지수 구해주기 # 지수 = m**2 도 됨
BMI = kg/m**2

In [ ]:
BMI

### Boolean 인덱싱
- 조건에 해당하는 (True)인 값들만 출력해준다

In [ ]:
#임의의 점수데이터 
score = np.array([80,75,55,96,30])
score

In [ ]:
#현재는 단순한 논리연산만 해준 결과
score>=80

In [ ]:
# 논리연산이 참인 결과값만 출력해준다
score[score>=80]

In [ ]:
name = np.array(['영화','새롬','성국','창규'])
name

In [ ]:
bol = np.array([False, True, False, True]) # 앞글자는 대문자로 쓸것
bol

In [ ]:
name[bol] # True 인 값만 가져옴

In [ ]:
score2 = np.array([[60,70],[70,80],[90,20],[100,60]])
score2

In [ ]:
# 내가 찾고자하는 이름이 있나?
name == '유미'

In [ ]:
name == '성국'

In [ ]:
score2[name=='성국'] # 인덱스 자기 자리 번호값으로만 감 , name=='성국' 은 위에 [2]번자리 true 값 그대로 
#score2 [2] 값으로 올라감

### 범용함수 (Universally Funtion)
- numpy에서 제공해주는 함수

In [ ]:

#sum() : 합계를 구해주는 함수
arr = np.array([1,2,3])
arr.sum()

In [ ]:
# arr2 라고 하는 변수에 랜덤수 (1~10)이 담긴 크기가 2행 5열인 배열 생성후 더하기
arr2=np.random.randint(1,11, size = (2,5))
print(arr2)
print(arr2.sum())

In [ ]:
np.sum(arr2) #<= 이렇게 써도 됨 또다른 방법으로 sum 함수 사용가능!

In [ ]:
# 평균을 구해주는 함수 : mean() -> 전체 요소값의 평균을 구해주는 함수
arr2.mean()

In [ ]:
# 제곱근을 구하는 함수 : sqrt
arr3 = np.array([1,4,9,16,25])
arr3

In [ ]:
arr3.sqrt() #<- 이렇게 쓰면 안됨

In [ ]:
np.sqrt(arr3) #<- 이렇게 써야 됨

In [ ]:
#절대값을 구해주는 함수 : abs()
np.abs([-1,2,-3,4,-5])

### 영화 평점 데이터 분석

In [28]:
# 데이터 가져오기!
m_data = np.loadtxt('ratings.txt', delimiter = '::',dtype='int') # delimiter = 구분 
# dtype='int' 닫는 소괄호 옆 + shift + tab : 툴팁 열어서 type 확인하고 float 타입을 -> int 타입으로 바꿔줌 
m_data
# 사용자 아이디, 영화 고유번호 , 영화 평점 , 영화 시간

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     6040,       562,         5, 956704746],
       [     6040,      1096,         4, 956715648],
       [     6040,      1097,         4, 956715569]])

In [ ]:
#차원 -> 2차원
m_data.ndim

In [ ]:
#크기 -> 1000209행 4열을 가지는 데이터
m_data.shape

In [ ]:
#데이터의 개수 -> 4000836개의 데이터
m_data.size

- 전체평점의 평균 구하기~

In [ ]:
#전체 자료에서 평점만 가져온 후에 평균 구해주기! -> 슬라이싱 이용하기
np.mean(m_data[:,2]) # 전체행에서 3열만 가져옴

### 사용자별 평점 평균 구하기
- 1번 사용자의 평점 평균 구하기

In [ ]:
# 데이터 중복을 제거하고 출력해주는 함수 : np.unique()
np.unique(m_data[:,0]) # 전체 행에서 0열만 가져옴
#사용자 아이디만 가져오기

In [ ]:
# 1번 아이디를 가진 사용자만 가져오기 
rating=np.unique(m_data[:,0])
rating

In [ ]:
# 전체에서 ==1 인 값을 논리값으로 true를 뱉어냄 그리고 m_data[true]값인 1인 데이터를 뱉음 (불리언 인덱싱)
user1 = m_data[m_data[:,0]==1]
user1

In [ ]:
# user1 의 전체 길이
len(user1)

In [ ]:
user1

In [ ]:
#인덱싱한 자료에서 평점만 가져오기 -> 평균구하기! 
avg1=np.mean(user1[:,2])
avg1
#user1[:,2].mean() 도 됨

- 전체 사용자의 각각 평균 평점 구해주기 !

In [38]:
user_uni=np.unique(m_data[:,0])
#반복문에 넣어주기 위함!
#id 정보만 가져오기
#user와 비교해서 불리언 인덱싱
#인덱싱 해온 자료에서 평점만 가져오기
#평균 구해주기

In [39]:
 m_data[m_data[:,0]==user]

array([[     6040,       573,         4, 956704056],
       [     6040,       589,         4, 956704996],
       [     6040,         1,         3, 957717358],
       ...,
       [     6040,       562,         5, 956704746],
       [     6040,      1096,         4, 956715648],
       [     6040,      1097,         4, 956715569]])

In [40]:
id=0;
for user in user_uni:
    id=id+1
    if user==id :
        data=m_data[m_data[:,0]==user]
        scoreavg=data[:,2].mean()
        print(f'{id}번 고객의 평점 평균은 {scoreavg}')
    

1번 고객의 평점 평균은 4.188679245283019
2번 고객의 평점 평균은 3.7131782945736433
3번 고객의 평점 평균은 3.9019607843137254
4번 고객의 평점 평균은 4.190476190476191
5번 고객의 평점 평균은 3.1464646464646466
6번 고객의 평점 평균은 3.9014084507042255
7번 고객의 평점 평균은 4.32258064516129
8번 고객의 평점 평균은 3.884892086330935
9번 고객의 평점 평균은 3.7358490566037736
10번 고객의 평점 평균은 4.114713216957606
11번 고객의 평점 평균은 3.2773722627737225
12번 고객의 평점 평균은 3.8260869565217392
13번 고객의 평점 평균은 3.388888888888889
14번 고객의 평점 평균은 3.32
15번 고객의 평점 평균은 3.3233830845771144
16번 고객의 평점 평균은 3.0285714285714285
17번 고객의 평점 평균은 4.075829383886256
18번 고객의 평점 평균은 3.6491803278688524
19번 고객의 평점 평균은 3.5725490196078433
20번 고객의 평점 평균은 4.083333333333333
21번 고객의 평점 평균은 2.909090909090909
22번 고객의 평점 평균은 3.0673400673400675
23번 고객의 평점 평균은 3.3157894736842106
24번 고객의 평점 평균은 3.948529411764706
25번 고객의 평점 평균은 3.7411764705882353
26번 고객의 평점 평균은 2.96
27번 고객의 평점 평균은 4.171428571428572
28번 고객의 평점 평균은 3.7570093457943927
29번 고객의 평점 평균은 3.5833333333333335
30번 고객의 평점 평균은 3.488372093023256
31번 고객의 평점 평균은 3.7310924369747

336번 고객의 평점 평균은 4.308411214953271
337번 고객의 평점 평균은 3.525252525252525
338번 고객의 평점 평균은 3.665745856353591
339번 고객의 평점 평균은 4.024193548387097
340번 고객의 평점 평균은 3.5277777777777777
341번 고객의 평점 평균은 4.2
342번 고객의 평점 평균은 3.6910569105691056
343번 고객의 평점 평균은 4.047138047138047
344번 고객의 평점 평균은 2.9555555555555557
345번 고객의 평점 평균은 4.4
346번 고객의 평점 평균은 4.307420494699647
347번 고객의 평점 평균은 3.878787878787879
348번 고객의 평점 평균은 3.78
349번 고객의 평점 평균은 3.25
350번 고객의 평점 평균은 3.9375
351번 고객의 평점 평균은 3.7572815533980584
352번 고객의 평점 평균은 3.4793103448275864
353번 고객의 평점 평균은 3.9166666666666665
354번 고객의 평점 평균은 3.586206896551724
355번 고객의 평점 평균은 3.4463007159904535
356번 고객의 평점 평균은 4.380952380952381
357번 고객의 평점 평균은 3.293103448275862
358번 고객의 평점 평균은 3.8472222222222223
359번 고객의 평점 평균은 3.857142857142857
360번 고객의 평점 평균은 3.6417910447761193
361번 고객의 평점 평균은 3.5384615384615383
362번 고객의 평점 평균은 3.290909090909091
363번 고객의 평점 평균은 3.744186046511628
364번 고객의 평점 평균은 3.142857142857143
365번 고객의 평점 평균은 3.3404255319148937
366번 고객의 평점 평균은 4.06949806949807
3

658번 고객의 평점 평균은 3.096774193548387
659번 고객의 평점 평균은 3.7
660번 고객의 평점 평균은 3.0170697012802274
661번 고객의 평점 평균은 4.647887323943662
662번 고객의 평점 평균은 3.141732283464567
663번 고객의 평점 평균은 3.580357142857143
664번 고객의 평점 평균은 4.025316455696203
665번 고객의 평점 평균은 3.5
666번 고객의 평점 평균은 3.8932038834951457
667번 고객의 평점 평균은 3.0935672514619883
668번 고객의 평점 평균은 3.5833333333333335
669번 고객의 평점 평균은 3.847255369928401
670번 고객의 평점 평균은 3.2444444444444445
671번 고객의 평점 평균은 4.2592592592592595
672번 고객의 평점 평균은 3.872340425531915
673번 고객의 평점 평균은 3.13151364764268
674번 고객의 평점 평균은 4.2784810126582276
675번 고객의 평점 평균은 3.3095238095238093
676번 고객의 평점 평균은 3.128205128205128
677번 고객의 평점 평균은 3.892682926829268
678번 고객의 평점 평균은 3.6776776776776776
679번 고객의 평점 평균은 3.926829268292683
680번 고객의 평점 평균은 3.5714285714285716
681번 고객의 평점 평균은 4.2368421052631575
682번 고객의 평점 평균은 4.733333333333333
683번 고객의 평점 평균은 3.586206896551724
684번 고객의 평점 평균은 3.8947368421052633
685번 고객의 평점 평균은 3.2357142857142858
686번 고객의 평점 평균은 3.7777777777777777
687번 고객의 평점 평균은 3.48734177215

976번 고객의 평점 평균은 3.3636363636363638
977번 고객의 평점 평균은 3.7625
978번 고객의 평점 평균은 3.8863636363636362
979번 고객의 평점 평균은 4.04054054054054
980번 고객의 평점 평균은 3.2222222222222223
981번 고객의 평점 평균은 3.3303964757709252
982번 고객의 평점 평균은 4.176470588235294
983번 고객의 평점 평균은 4.115384615384615
984번 고객의 평점 평균은 3.5417867435158503
985번 고객의 평점 평균은 4.212328767123288
986번 고객의 평점 평균은 3.772727272727273
987번 고객의 평점 평균은 4.017045454545454
988번 고객의 평점 평균은 3.8493150684931505
989번 고객의 평점 평균은 4.681818181818182
990번 고객의 평점 평균은 3.549019607843137
991번 고객의 평점 평균은 3.75
992번 고객의 평점 평균은 3.4193548387096775
993번 고객의 평점 평균은 3.3448275862068964
994번 고객의 평점 평균은 4.153846153846154
995번 고객의 평점 평균은 3.8979591836734695
996번 고객의 평점 평균은 3.935810810810811
997번 고객의 평점 평균은 3.933333333333333
998번 고객의 평점 평균은 4.118518518518519
999번 고객의 평점 평균은 3.186893203883495
1000번 고객의 평점 평균은 4.130952380952381
1001번 고객의 평점 평균은 3.6525198938992043
1002번 고객의 평점 평균은 4.136363636363637
1003번 고객의 평점 평균은 4.137931034482759
1004번 고객의 평점 평균은 3.1600831600831603
1005번 고객의 평점 평균은 4.1413

1299번 고객의 평점 평균은 3.7905982905982905
1300번 고객의 평점 평균은 3.4819277108433737
1301번 고객의 평점 평균은 3.774410774410774
1302번 고객의 평점 평균은 4.266666666666667
1303번 고객의 평점 평균은 3.3205317577548006
1304번 고객의 평점 평균은 3.9642857142857144
1305번 고객의 평점 평균은 4.333333333333333
1306번 고객의 평점 평균은 4.1475054229934925
1307번 고객의 평점 평균은 4.333333333333333
1308번 고객의 평점 평균은 3.606741573033708
1309번 고객의 평점 평균은 3.7083333333333335
1310번 고객의 평점 평균은 3.75
1311번 고객의 평점 평균은 3.478723404255319
1312번 고객의 평점 평균은 3.270967741935484
1313번 고객의 평점 평균은 3.6551724137931036
1314번 고객의 평점 평균은 2.789473684210526
1315번 고객의 평점 평균은 4.505376344086022
1316번 고객의 평점 평균은 3.236842105263158
1317번 고객의 평점 평균은 3.6620775969962454
1318번 고객의 평점 평균은 3.0476190476190474
1319번 고객의 평점 평균은 3.2142857142857144
1320번 고객의 평점 평균은 4.017094017094017
1321번 고객의 평점 평균은 3.2923976608187133
1322번 고객의 평점 평균은 4.1171875
1323번 고객의 평점 평균은 3.7027027027027026
1324번 고객의 평점 평균은 4.037037037037037
1325번 고객의 평점 평균은 3.9858156028368796
1326번 고객의 평점 평균은 3.918918918918919
1327번 고객의 평점 평균은 3.507042253

1607번 고객의 평점 평균은 3.1847826086956523
1608번 고객의 평점 평균은 2.0833333333333335
1609번 고객의 평점 평균은 3.4206128133704734
1610번 고객의 평점 평균은 3.9642857142857144
1611번 고객의 평점 평균은 3.573741007194245
1612번 고객의 평점 평균은 3.652173913043478
1613번 고객의 평점 평균은 3.4264150943396228
1614번 고객의 평점 평균은 3.3934426229508197
1615번 고객의 평점 평균은 3.0476190476190474
1616번 고객의 평점 평균은 3.1338582677165356
1617번 고객의 평점 평균은 3.0833333333333335
1618번 고객의 평점 평균은 4.208791208791209
1619번 고객의 평점 평균은 4.03030303030303
1620번 고객의 평점 평균은 3.9444444444444446
1621번 고객의 평점 평균은 3.1363636363636362
1622번 고객의 평점 평균은 3.730769230769231
1623번 고객의 평점 평균은 4.214285714285714
1624번 고객의 평점 평균은 3.005714285714286
1625번 고객의 평점 평균은 3.3555555555555556
1626번 고객의 평점 평균은 3.4391143911439115
1627번 고객의 평점 평균은 2.9791666666666665
1628번 고객의 평점 평균은 3.745011086474501
1629번 고객의 평점 평균은 3.4923076923076923
1630번 고객의 평점 평균은 2.264957264957265
1631번 고객의 평점 평균은 3.8423076923076924
1632번 고객의 평점 평균은 2.7760416666666665
1633번 고객의 평점 평균은 2.9705882352941178
1634번 고객의 평점 평균은 3.5849056603773586
16

1926번 고객의 평점 평균은 4.085470085470085
1927번 고객의 평점 평균은 3.9545454545454546
1928번 고객의 평점 평균은 3.839622641509434
1929번 고객의 평점 평균은 3.5555555555555554
1930번 고객의 평점 평균은 3.1666666666666665
1931번 고객의 평점 평균은 3.616279069767442
1932번 고객의 평점 평균은 3.6666666666666665
1933번 고객의 평점 평균은 3.466666666666667
1934번 고객의 평점 평균은 3.0847457627118646
1935번 고객의 평점 평균은 3.4827586206896552
1936번 고객의 평점 평균은 3.7142857142857144
1937번 고객의 평점 평균은 3.183050847457627
1938번 고객의 평점 평균은 3.1314285714285712
1939번 고객의 평점 평균은 3.7782805429864252
1940번 고객의 평점 평균은 4.671875
1941번 고객의 평점 평균은 3.0545454545454547
1942번 고객의 평점 평균은 2.864406779661017
1943번 고객의 평점 평균은 3.6205882352941177
1944번 고객의 평점 평균은 3.911764705882353
1945번 고객의 평점 평균은 2.7945205479452055
1946번 고객의 평점 평균은 3.858974358974359
1947번 고객의 평점 평균은 3.9523809523809526
1948번 고객의 평점 평균은 3.1091954022988504
1949번 고객의 평점 평균은 4.176470588235294
1950번 고객의 평점 평균은 3.5182481751824817
1951번 고객의 평점 평균은 3.015625
1952번 고객의 평점 평균은 3.49003984063745
1953번 고객의 평점 평균은 3.7941176470588234
1954번 고객의 평점 평균은 3.9337

2229번 고객의 평점 평균은 3.4871794871794872
2230번 고객의 평점 평균은 3.188841201716738
2231번 고객의 평점 평균은 3.6720183486238533
2232번 고객의 평점 평균은 4.050314465408805
2233번 고객의 평점 평균은 3.3381642512077296
2234번 고객의 평점 평균은 3.9047619047619047
2235번 고객의 평점 평균은 3.908450704225352
2236번 고객의 평점 평균은 3.694736842105263
2237번 고객의 평점 평균은 3.916289592760181
2238번 고객의 평점 평균은 3.75
2239번 고객의 평점 평균은 4.092436974789916
2240번 고객의 평점 평균은 4.282828282828283
2241번 고객의 평점 평균은 4.25
2242번 고객의 평점 평균은 3.6536144578313254
2243번 고객의 평점 평균은 4.683333333333334
2244번 고객의 평점 평균은 3.400932400932401
2245번 고객의 평점 평균은 3.0980392156862746
2246번 고객의 평점 평균은 3.6744186046511627
2247번 고객의 평점 평균은 3.922178988326848
2248번 고객의 평점 평균은 3.7476635514018692
2249번 고객의 평점 평균은 3.9285714285714284
2250번 고객의 평점 평균은 3.074626865671642
2251번 고객의 평점 평균은 3.6610169491525424
2252번 고객의 평점 평균은 3.4782608695652173
2253번 고객의 평점 평균은 4.096774193548387
2254번 고객의 평점 평균은 3.9642857142857144
2255번 고객의 평점 평균은 3.6685714285714286
2256번 고객의 평점 평균은 4.0
2257번 고객의 평점 평균은 3.5428571428571427
2258번 고객의 평

2476번 고객의 평점 평균은 4.163934426229508
2477번 고객의 평점 평균은 4.475409836065574
2478번 고객의 평점 평균은 3.5505226480836236
2479번 고객의 평점 평균은 3.8484848484848486
2480번 고객의 평점 평균은 3.8666666666666667
2481번 고객의 평점 평균은 3.909090909090909
2482번 고객의 평점 평균은 3.5
2483번 고객의 평점 평균은 3.9
2484번 고객의 평점 평균은 3.3692870201096894
2485번 고객의 평점 평균은 3.6707317073170733
2486번 고객의 평점 평균은 3.8051948051948052
2487번 고객의 평점 평균은 3.7027027027027026
2488번 고객의 평점 평균은 4.2
2489번 고객의 평점 평균은 3.397984886649874
2490번 고객의 평점 평균은 3.5454545454545454
2491번 고객의 평점 평균은 3.0350877192982457
2492번 고객의 평점 평균은 3.764044943820225
2493번 고객의 평점 평균은 3.5348837209302326
2494번 고객의 평점 평균은 3.0
2495번 고객의 평점 평균은 3.4871794871794872
2496번 고객의 평점 평균은 2.9902152641878668
2497번 고객의 평점 평균은 4.5041322314049586
2498번 고객의 평점 평균은 3.168831168831169
2499번 고객의 평점 평균은 3.617021276595745
2500번 고객의 평점 평균은 3.6357142857142857
2501번 고객의 평점 평균은 3.9058823529411764
2502번 고객의 평점 평균은 3.9047619047619047
2503번 고객의 평점 평균은 3.02
2504번 고객의 평점 평균은 3.558139534883721
2505번 고객의 평점 평균은 4.09375
2506번 고객의 평점 

2741번 고객의 평점 평균은 4.0
2742번 고객의 평점 평균은 2.861111111111111
2743번 고객의 평점 평균은 3.569476082004556
2744번 고객의 평점 평균은 1.3043478260869565
2745번 고객의 평점 평균은 3.8527918781725887
2746번 고객의 평점 평균은 3.8771929824561404
2747번 고객의 평점 평균은 4.302158273381295
2748번 고객의 평점 평균은 2.708588957055215
2749번 고객의 평점 평균은 3.9555555555555557
2750번 고객의 평점 평균은 4.295
2751번 고객의 평점 평균은 3.4269662921348316
2752번 고객의 평점 평균은 3.2962962962962963
2753번 고객의 평점 평균은 3.784158415841584
2754번 고객의 평점 평균은 3.79
2755번 고객의 평점 평균은 4.434782608695652
2756번 고객의 평점 평균은 4.03765690376569
2757번 고객의 평점 평균은 3.953488372093023
2758번 고객의 평점 평균은 4.0
2759번 고객의 평점 평균은 3.55
2760번 고객의 평점 평균은 4.102941176470588
2761번 고객의 평점 평균은 3.515527950310559
2762번 고객의 평점 평균은 4.0
2763번 고객의 평점 평균은 2.76
2764번 고객의 평점 평균은 4.186440677966102
2765번 고객의 평점 평균은 3.6208530805687205
2766번 고객의 평점 평균은 4.137254901960785
2767번 고객의 평점 평균은 3.269230769230769
2768번 고객의 평점 평균은 4.0375
2769번 고객의 평점 평균은 3.7534246575342465
2770번 고객의 평점 평균은 4.1063829787234045
2771번 고객의 평점 평균은 2.940766550522648
2772번 고객의 평

3007번 고객의 평점 평균은 2.8702928870292888
3008번 고객의 평점 평균은 3.823529411764706
3009번 고객의 평점 평균은 4.0
3010번 고객의 평점 평균은 3.4380952380952383
3011번 고객의 평점 평균은 4.315217391304348
3012번 고객의 평점 평균은 2.5062111801242235
3013번 고객의 평점 평균은 3.4539614561027836
3014번 고객의 평점 평균은 3.570588235294118
3015번 고객의 평점 평균은 3.4285714285714284
3016번 고객의 평점 평균은 3.8292682926829267
3017번 고객의 평점 평균은 3.2845303867403315
3018번 고객의 평점 평균은 3.7
3019번 고객의 평점 평균은 4.148148148148148
3020번 고객의 평점 평균은 4.017647058823529
3021번 고객의 평점 평균은 3.25
3022번 고객의 평점 평균은 3.006666666666667
3023번 고객의 평점 평균은 3.5161290322580645
3024번 고객의 평점 평균은 3.63302752293578
3025번 고객의 평점 평균은 4.108108108108108
3026번 고객의 평점 평균은 2.761904761904762
3027번 고객의 평점 평균은 4.217391304347826
3028번 고객의 평점 평균은 3.743362831858407
3029번 고객의 평점 평균은 3.914586070959264
3030번 고객의 평점 평균은 3.769230769230769
3031번 고객의 평점 평균은 3.904
3032번 고객의 평점 평균은 4.278704612365064
3033번 고객의 평점 평균은 3.601503759398496
3034번 고객의 평점 평균은 3.9285714285714284
3035번 고객의 평점 평균은 3.8125
3036번 고객의 평점 평균은 4.525862068965517
3037번 

3265번 고객의 평점 평균은 2.8484251968503935
3266번 고객의 평점 평균은 4.357615894039735
3267번 고객의 평점 평균은 3.857142857142857
3268번 고객의 평점 평균은 3.8656716417910446
3269번 고객의 평점 평균은 3.855421686746988
3270번 고객의 평점 평균은 3.6639344262295084
3271번 고객의 평점 평균은 3.8214285714285716
3272번 고객의 평점 평균은 3.77511961722488
3273번 고객의 평점 평균은 4.1
3274번 고객의 평점 평균은 3.242424242424242
3275번 고객의 평점 평균은 3.4761904761904763
3276번 고객의 평점 평균은 3.0689655172413794
3277번 고객의 평점 평균은 4.053333333333334
3278번 고객의 평점 평균은 3.869565217391304
3279번 고객의 평점 평균은 2.6857142857142855
3280번 고객의 평점 평균은 2.782742681047766
3281번 고객의 평점 평균은 4.031578947368421
3282번 고객의 평점 평균은 4.5
3283번 고객의 평점 평균은 3.597560975609756
3284번 고객의 평점 평균은 4.2926829268292686
3285번 고객의 평점 평균은 3.419457735247209
3286번 고객의 평점 평균은 4.285714285714286
3287번 고객의 평점 평균은 4.583333333333333
3288번 고객의 평점 평균은 3.576923076923077
3289번 고객의 평점 평균은 3.84
3290번 고객의 평점 평균은 2.6818181818181817
3291번 고객의 평점 평균은 3.75
3292번 고객의 평점 평균은 4.021299254526092
3293번 고객의 평점 평균은 3.2888888888888888
3294번 고객의 평점 평균은 4.11340206185

3521번 고객의 평점 평균은 3.7906976744186047
3522번 고객의 평점 평균은 4.032258064516129
3523번 고객의 평점 평균은 3.8205128205128207
3524번 고객의 평점 평균은 3.5751633986928106
3525번 고객의 평점 평균은 3.477777777777778
3526번 고객의 평점 평균은 2.8399168399168397
3527번 고객의 평점 평균은 3.5641025641025643
3528번 고객의 평점 평균은 2.5714285714285716
3529번 고객의 평점 평균은 3.0352422907488985
3530번 고객의 평점 평균은 3.75
3531번 고객의 평점 평균은 4.233766233766234
3532번 고객의 평점 평균은 3.8596491228070176
3533번 고객의 평점 평균은 3.5543478260869565
3534번 고객의 평점 평균은 4.072727272727272
3535번 고객의 평점 평균은 3.9655172413793105
3536번 고객의 평점 평균은 3.7636363636363637
3537번 고객의 평점 평균은 2.456140350877193
3538번 고객의 평점 평균은 3.773006134969325
3539번 고객의 평점 평균은 4.038033395176252
3540번 고객의 평점 평균은 4.110576923076923
3541번 고객의 평점 평균은 4.228571428571429
3542번 고객의 평점 평균은 3.1818181818181817
3543번 고객의 평점 평균은 3.605769230769231
3544번 고객의 평점 평균은 4.344827586206897
3545번 고객의 평점 평균은 3.4285714285714284
3546번 고객의 평점 평균은 3.392682926829268
3547번 고객의 평점 평균은 3.5359116022099446
3548번 고객의 평점 평균은 2.5384615384615383
3549번 고객의 평점 평균은 3

3784번 고객의 평점 평균은 3.7804878048780486
3785번 고객의 평점 평균은 3.2
3786번 고객의 평점 평균은 4.031746031746032
3787번 고객의 평점 평균은 4.05
3788번 고객의 평점 평균은 3.75
3789번 고객의 평점 평균은 4.231788079470198
3790번 고객의 평점 평균은 4.264
3791번 고객의 평점 평균은 3.388888888888889
3792번 고객의 평점 평균은 3.5761266747868454
3793번 고객의 평점 평균은 2.789473684210526
3794번 고객의 평점 평균은 3.0681818181818183
3795번 고객의 평점 평균은 4.137931034482759
3796번 고객의 평점 평균은 4.014851485148514
3797번 고객의 평점 평균은 3.4814814814814814
3798번 고객의 평점 평균은 3.6333333333333333
3799번 고객의 평점 평균은 3.9921875
3800번 고객의 평점 평균은 3.492957746478873
3801번 고객의 평점 평균은 3.8142857142857145
3802번 고객의 평점 평균은 3.1818181818181817
3803번 고객의 평점 평균은 3.6363636363636362
3804번 고객의 평점 평균은 3.5614973262032086
3805번 고객의 평점 평균은 3.7837837837837838
3806번 고객의 평점 평균은 2.9580838323353293
3807번 고객의 평점 평균은 3.3410041841004183
3808번 고객의 평점 평균은 2.9844559585492227
3809번 고객의 평점 평균은 4.404255319148936
3810번 고객의 평점 평균은 4.402985074626866
3811번 고객의 평점 평균은 3.8
3812번 고객의 평점 평균은 3.526315789473684
3813번 고객의 평점 평균은 4.447761194029851
3814번 고객의 평

4044번 고객의 평점 평균은 4.225806451612903
4045번 고객의 평점 평균은 3.522727272727273
4046번 고객의 평점 평균은 3.5675675675675675
4047번 고객의 평점 평균은 4.288888888888889
4048번 고객의 평점 평균은 3.7544581618655695
4049번 고객의 평점 평균은 3.32
4050번 고객의 평점 평균은 4.2976190476190474
4051번 고객의 평점 평균은 2.91
4052번 고객의 평점 평균은 4.235294117647059
4053번 고객의 평점 평균은 3.47
4054번 고객의 평점 평균은 3.663961038961039
4055번 고객의 평점 평균은 2.8574938574938575
4056번 고객의 평점 평균은 2.3181818181818183
4057번 고객의 평점 평균은 3.526315789473684
4058번 고객의 평점 평균은 3.405566600397614
4059번 고객의 평점 평균은 3.111111111111111
4060번 고객의 평점 평균은 3.8515625
4061번 고객의 평점 평균은 3.236842105263158
4062번 고객의 평점 평균은 3.437888198757764
4063번 고객의 평점 평균은 3.8983050847457625
4064번 고객의 평점 평균은 3.0822596630327057
4065번 고객의 평점 평균은 4.190476190476191
4066번 고객의 평점 평균은 3.168421052631579
4067번 고객의 평점 평균은 2.95
4068번 고객의 평점 평균은 4.15
4069번 고객의 평점 평균은 3.870967741935484
4070번 고객의 평점 평균은 3.6074074074074076
4071번 고객의 평점 평균은 3.954954954954955
4072번 고객의 평점 평균은 3.6968503937007875
4073번 고객의 평점 평균은 3.75
4074번 고객의 평점 평균은 3.96153846

4302번 고객의 평점 평균은 3.8821138211382116
4303번 고객의 평점 평균은 3.6737967914438503
4304번 고객의 평점 평균은 4.2
4305번 고객의 평점 평균은 3.7244897959183674
4306번 고객의 평점 평균은 3.6483516483516483
4307번 고객의 평점 평균은 3.7058823529411766
4308번 고객의 평점 평균은 3.2403846153846154
4309번 고객의 평점 평균은 3.8181818181818183
4310번 고객의 평점 평균은 3.8754208754208754
4311번 고객의 평점 평균은 2.9468085106382977
4312번 고객의 평점 평균은 3.278595696489241
4313번 고객의 평점 평균은 4.083333333333333
4314번 고객의 평점 평균은 3.787878787878788
4315번 고객의 평점 평균은 3.8774193548387097
4316번 고객의 평점 평균은 3.4871794871794872
4317번 고객의 평점 평균은 3.5686274509803924
4318번 고객의 평점 평균은 3.847916666666667
4319번 고객의 평점 평균은 3.8627450980392157
4320번 고객의 평점 평균은 4.2592592592592595
4321번 고객의 평점 평균은 3.9649122807017543
4322번 고객의 평점 평균은 3.437974683544304
4323번 고객의 평점 평균은 3.576642335766423
4324번 고객의 평점 평균은 4.2727272727272725
4325번 고객의 평점 평균은 3.0
4326번 고객의 평점 평균은 3.622047244094488
4327번 고객의 평점 평균은 4.12962962962963
4328번 고객의 평점 평균은 3.6732673267326734
4329번 고객의 평점 평균은 3.488372093023256
4330번 고객의 평점 평균은 3.6341463414634

4557번 고객의 평점 평균은 3.627906976744186
4558번 고객의 평점 평균은 4.238095238095238
4559번 고객의 평점 평균은 4.27906976744186
4560번 고객의 평점 평균은 3.574829931972789
4561번 고객의 평점 평균은 3.8363636363636364
4562번 고객의 평점 평균은 3.589403973509934
4563번 고객의 평점 평균은 4.35
4564번 고객의 평점 평균은 3.9615384615384617
4565번 고객의 평점 평균은 3.9722222222222223
4566번 고객의 평점 평균은 3.616883116883117
4567번 고객의 평점 평균은 4.068181818181818
4568번 고객의 평점 평균은 3.6
4569번 고객의 평점 평균은 3.7093023255813953
4570번 고객의 평점 평균은 3.4473684210526314
4571번 고객의 평점 평균은 3.9215686274509802
4572번 고객의 평점 평균은 3.924137931034483
4573번 고객의 평점 평균은 3.6948051948051948
4574번 고객의 평점 평균은 3.7
4575번 고객의 평점 평균은 2.088
4576번 고객의 평점 평균은 4.0
4577번 고객의 평점 평균은 3.2674418604651163
4578번 고객의 평점 평균은 3.7303571428571427
4579번 고객의 평점 평균은 3.6516690856313496
4580번 고객의 평점 평균은 3.9197080291970803
4581번 고객의 평점 평균은 3.6506024096385543
4582번 고객의 평점 평균은 4.195652173913044
4583번 고객의 평점 평균은 3.6666666666666665
4584번 고객의 평점 평균은 4.580645161290323
4585번 고객의 평점 평균은 3.8286604361370715
4586번 고객의 평점 평균은 4.076923076923077
4587

4813번 고객의 평점 평균은 4.1826923076923075
4814번 고객의 평점 평균은 3.4545454545454546
4815번 고객의 평점 평균은 4.405405405405405
4816번 고객의 평점 평균은 4.223118279569892
4817번 고객의 평점 평균은 4.380434782608695
4818번 고객의 평점 평균은 3.96
4819번 고객의 평점 평균은 3.793040293040293
4820번 고객의 평점 평균은 3.4444444444444446
4821번 고객의 평점 평균은 3.4401709401709404
4822번 고객의 평점 평균은 3.392857142857143
4823번 고객의 평점 평균은 3.3382978723404255
4824번 고객의 평점 평균은 3.7709251101321586
4825번 고객의 평점 평균은 3.938775510204082
4826번 고객의 평점 평균은 3.754601226993865
4827번 고객의 평점 평균은 3.375
4828번 고객의 평점 평균은 3.62
4829번 고객의 평점 평균은 3.780185758513932
4830번 고객의 평점 평균은 3.5350877192982457
4831번 고객의 평점 평균은 4.10126582278481
4832번 고객의 평점 평균은 3.7709923664122136
4833번 고객의 평점 평균은 4.037037037037037
4834번 고객의 평점 평균은 3.6285714285714286
4835번 고객의 평점 평균은 3.7228915662650603
4836번 고객의 평점 평균은 3.476923076923077
4837번 고객의 평점 평균은 3.274390243902439
4838번 고객의 평점 평균은 3.8205128205128207
4839번 고객의 평점 평균은 3.0434782608695654
4840번 고객의 평점 평균은 3.736111111111111
4841번 고객의 평점 평균은 3.641304347826087
4842번 고객의 평점

5063번 고객의 평점 평균은 3.849557522123894
5064번 고객의 평점 평균은 4.070707070707071
5065번 고객의 평점 평균은 3.6830188679245284
5066번 고객의 평점 평균은 4.121212121212121
5067번 고객의 평점 평균은 4.142857142857143
5068번 고객의 평점 평균은 4.054545454545455
5069번 고객의 평점 평균은 4.76
5070번 고객의 평점 평균은 3.5471311475409837
5071번 고객의 평점 평균은 4.1234567901234565
5072번 고객의 평점 평균은 4.271186440677966
5073번 고객의 평점 평균은 4.52
5074번 고객의 평점 평균은 3.433639947437582
5075번 고객의 평점 평균은 4.258620689655173
5076번 고객의 평점 평균은 3.4403669724770642
5077번 고객의 평점 평균은 3.5919811320754715
5078번 고객의 평점 평균은 3.966666666666667
5079번 고객의 평점 평균은 3.4285714285714284
5080번 고객의 평점 평균은 4.0
5081번 고객의 평점 평균은 3.801980198019802
5082번 고객의 평점 평균은 3.7672413793103448
5083번 고객의 평점 평균은 3.557894736842105
5084번 고객의 평점 평균은 2.8496240601503757
5085번 고객의 평점 평균은 4.411764705882353
5086번 고객의 평점 평균은 3.968944099378882
5087번 고객의 평점 평균은 3.5135135135135136
5088번 고객의 평점 평균은 4.193548387096774
5089번 고객의 평점 평균은 3.909090909090909
5090번 고객의 평점 평균은 4.15
5091번 고객의 평점 평균은 3.75
5092번 고객의 평점 평균은 4.056338028169014
5093번 고

5312번 고객의 평점 평균은 3.8652777777777776
5313번 고객의 평점 평균은 4.125
5314번 고객의 평점 평균은 3.6
5315번 고객의 평점 평균은 4.0285714285714285
5316번 고객의 평점 평균은 3.8974358974358974
5317번 고객의 평점 평균은 4.047882136279926
5318번 고객의 평점 평균은 3.6262626262626263
5319번 고객의 평점 평균은 3.814432989690722
5320번 고객의 평점 평균은 2.652173913043478
5321번 고객의 평점 평균은 3.09375
5322번 고객의 평점 평균은 3.892156862745098
5323번 고객의 평점 평균은 3.6991869918699187
5324번 고객의 평점 평균은 3.9364161849710984
5325번 고객의 평점 평균은 3.375
5326번 고객의 평점 평균은 2.40625
5327번 고객의 평점 평균은 3.8282208588957056
5328번 고객의 평점 평균은 3.641509433962264
5329번 고객의 평점 평균은 4.130514705882353
5330번 고객의 평점 평균은 3.338709677419355
5331번 고객의 평점 평균은 3.3375
5332번 고객의 평점 평균은 4.397260273972603
5333번 고객의 평점 평균은 3.5530393325387366
5334번 고객의 평점 평균은 1.9272727272727272
5335번 고객의 평점 평균은 3.9683544303797467
5336번 고객의 평점 평균은 4.382978723404255
5337번 고객의 평점 평균은 4.214689265536723
5338번 고객의 평점 평균은 3.798076923076923
5339번 고객의 평점 평균은 3.7777777777777777
5340번 고객의 평점 평균은 3.616822429906542
5341번 고객의 평점 평균은 3.6587301587301586
5342번 고

5610번 고객의 평점 평균은 4.2
5611번 고객의 평점 평균은 4.258064516129032
5612번 고객의 평점 평균은 2.9722222222222223
5613번 고객의 평점 평균은 3.63953488372093
5614번 고객의 평점 평균은 3.805256869772999
5615번 고객의 평점 평균은 3.4602649006622515
5616번 고객의 평점 평균은 3.853846153846154
5617번 고객의 평점 평균은 3.5405405405405403
5618번 고객의 평점 평균은 3.8979591836734695
5619번 고객의 평점 평균은 3.652173913043478
5620번 고객의 평점 평균은 3.4246575342465753
5621번 고객의 평점 평균은 3.0251572327044025
5622번 고객의 평점 평균은 4.127906976744186
5623번 고객의 평점 평균은 3.9015151515151514
5624번 고객의 평점 평균은 3.3529411764705883
5625번 고객의 평점 평균은 3.9078947368421053
5626번 고객의 평점 평균은 4.38728323699422
5627번 고객의 평점 평균은 2.996319018404908
5628번 고객의 평점 평균은 3.4347826086956523
5629번 고객의 평점 평균은 4.475247524752476
5630번 고객의 평점 평균은 4.2091254752851714
5631번 고객의 평점 평균은 4.177215189873418
5632번 고객의 평점 평균은 3.65
5633번 고객의 평점 평균은 3.8205128205128207
5634번 고객의 평점 평균은 3.73
5635번 고객의 평점 평균은 3.5833333333333335
5636번 고객의 평점 평균은 3.1580188679245285
5637번 고객의 평점 평균은 3.9347826086956523
5638번 고객의 평점 평균은 3.519607843137255
5639번 고객의 평점

5855번 고객의 평점 평균은 4.03921568627451
5856번 고객의 평점 평균은 3.65625
5857번 고객의 평점 평균은 3.33
5858번 고객의 평점 평균은 4.07
5859번 고객의 평점 평균은 4.0
5860번 고객의 평점 평균은 3.8987341772151898
5861번 고객의 평점 평균은 3.770053475935829
5862번 고객의 평점 평균은 4.6
5863번 고객의 평점 평균은 3.9047619047619047
5864번 고객의 평점 평균은 4.205128205128205
5865번 고객의 평점 평균은 3.3300970873786406
5866번 고객의 평점 평균은 3.875
5867번 고객의 평점 평균은 3.6875
5868번 고객의 평점 평균은 4.134328358208955
5869번 고객의 평점 평균은 3.5789473684210527
5870번 고객의 평점 평균은 3.9743589743589745
5871번 고객의 평점 평균은 4.17
5872번 고객의 평점 평균은 3.3688212927756656
5873번 고객의 평점 평균은 4.242424242424242
5874번 고객의 평점 평균은 3.5451505016722407
5875번 고객의 평점 평균은 3.8333333333333335
5876번 고객의 평점 평균은 3.8260869565217392
5877번 고객의 평점 평균은 3.6818181818181817
5878번 고객의 평점 평균은 3.632279534109817
5879번 고객의 평점 평균은 3.7818181818181817
5880번 고객의 평점 평균은 3.2085561497326203
5881번 고객의 평점 평균은 3.567857142857143
5882번 고객의 평점 평균은 3.7
5883번 고객의 평점 평균은 3.3461538461538463
5884번 고객의 평점 평균은 3.8846153846153846
5885번 고객의 평점 평균은 4.082644628099174
5886번 고객의 평점 평균은

In [33]:
for user in user_uni:
    user_id = m_data[:,0]
    user_data=m_data[user_id==user]
    user_score=user_data[:,2]
    print(f'{user}번의 평균 평점은 {user_score.mean()}입니다.')
    

1번의 평균 평점은 4.188679245283019입니다.
2번의 평균 평점은 3.7131782945736433입니다.
3번의 평균 평점은 3.9019607843137254입니다.
4번의 평균 평점은 4.190476190476191입니다.
5번의 평균 평점은 3.1464646464646466입니다.
6번의 평균 평점은 3.9014084507042255입니다.
7번의 평균 평점은 4.32258064516129입니다.
8번의 평균 평점은 3.884892086330935입니다.
9번의 평균 평점은 3.7358490566037736입니다.
10번의 평균 평점은 4.114713216957606입니다.
11번의 평균 평점은 3.2773722627737225입니다.
12번의 평균 평점은 3.8260869565217392입니다.
13번의 평균 평점은 3.388888888888889입니다.
14번의 평균 평점은 3.32입니다.
15번의 평균 평점은 3.3233830845771144입니다.
16번의 평균 평점은 3.0285714285714285입니다.
17번의 평균 평점은 4.075829383886256입니다.
18번의 평균 평점은 3.6491803278688524입니다.
19번의 평균 평점은 3.5725490196078433입니다.
20번의 평균 평점은 4.083333333333333입니다.
21번의 평균 평점은 2.909090909090909입니다.
22번의 평균 평점은 3.0673400673400675입니다.
23번의 평균 평점은 3.3157894736842106입니다.
24번의 평균 평점은 3.948529411764706입니다.
25번의 평균 평점은 3.7411764705882353입니다.
26번의 평균 평점은 2.96입니다.
27번의 평균 평점은 4.171428571428572입니다.
28번의 평균 평점은 3.7570093457943927입니다.
29번의 평균 평점은 3.5833333333333335입니다.
30번의 평균 평점은 3.488372093023256입니다.


255번의 평균 평점은 4.016393442622951입니다.
256번의 평균 평점은 3.8526315789473684입니다.
257번의 평균 평점은 4.452830188679245입니다.
258번의 평균 평점은 3.717241379310345입니다.
259번의 평균 평점은 4.0359712230215825입니다.
260번의 평균 평점은 3.311688311688312입니다.
261번의 평균 평점은 3.5762711864406778입니다.
262번의 평균 평점은 3.330188679245283입니다.
263번의 평균 평점은 3.6630434782608696입니다.
264번의 평균 평점은 2.785416666666667입니다.
265번의 평균 평점은 4.1938775510204085입니다.
266번의 평균 평점은 4.52입니다.
267번의 평균 평점은 3.3893129770992365입니다.
268번의 평균 평점은 3.3946360153256707입니다.
269번의 평균 평점은 3.8입니다.
270번의 평균 평점은 4.198412698412699입니다.
271번의 평균 평점은 3.9583333333333335입니다.
272번의 평균 평점은 3.6535269709543567입니다.
273번의 평균 평점은 3.727272727272727입니다.
274번의 평균 평점은 4.243243243243243입니다.
275번의 평균 평점은 4.247191011235955입니다.
276번의 평균 평점은 3.5217391304347827입니다.
277번의 평균 평점은 3.727272727272727입니다.
278번의 평균 평점은 3.9646464646464645입니다.
279번의 평균 평점은 2.872340425531915입니다.
280번의 평균 평점은 3.94입니다.
281번의 평균 평점은 3.891891891891892입니다.
282번의 평균 평점은 3.5172413793103448입니다.
283번의 평균 평점은 4.962962962962963입니다.
284번의 평균 평점은 

501번의 평균 평점은 3.417910447761194입니다.
502번의 평균 평점은 4.083333333333333입니다.
503번의 평균 평점은 4.448275862068965입니다.
504번의 평균 평점은 3.8055555555555554입니다.
505번의 평균 평점은 4.217391304347826입니다.
506번의 평균 평점은 3.422222222222222입니다.
507번의 평균 평점은 3.9523809523809526입니다.
508번의 평균 평점은 3.3221476510067114입니다.
509번의 평균 평점은 3.3139695712309822입니다.
510번의 평균 평점은 3.8282828282828283입니다.
511번의 평균 평점은 3.740740740740741입니다.
512번의 평균 평점은 3.8378378378378377입니다.
513번의 평균 평점은 3.1474358974358974입니다.
514번의 평균 평점은 4.2025316455696204입니다.
515번의 평균 평점은 3.728395061728395입니다.
516번의 평균 평점은 2.931972789115646입니다.
517번의 평균 평점은 3.963855421686747입니다.
518번의 평균 평점은 4.3478260869565215입니다.
519번의 평균 평점은 3.3777777777777778입니다.
520번의 평균 평점은 3.9363057324840764입니다.
521번의 평균 평점은 4.2926829268292686입니다.
522번의 평균 평점은 3.8448275862068964입니다.
523번의 평균 평점은 4.06입니다.
524번의 평균 평점은 3.608267716535433입니다.
525번의 평균 평점은 4.025입니다.
526번의 평균 평점은 3.896551724137931입니다.
527번의 평균 평점은 4.08입니다.
528번의 평균 평점은 3.3551724137931034입니다.
529번의 평균 평점은 4.19672131147541입니다.
530번의 평균 평

754번의 평균 평점은 3.7770700636942673입니다.
755번의 평균 평점은 4.111111111111111입니다.
756번의 평균 평점은 3.9714285714285715입니다.
757번의 평균 평점은 3.225806451612903입니다.
758번의 평균 평점은 4.0입니다.
759번의 평균 평점은 3.5876288659793816입니다.
760번의 평균 평점은 4.265625입니다.
761번의 평균 평점은 4.55입니다.
762번의 평균 평점은 3.717391304347826입니다.
763번의 평균 평점은 3.730769230769231입니다.
764번의 평균 평점은 4.525179856115108입니다.
765번의 평균 평점은 3.574626865671642입니다.
766번의 평균 평점은 3.9361702127659575입니다.
767번의 평균 평점은 4.023529411764706입니다.
768번의 평균 평점은 4.4375입니다.
769번의 평균 평점은 3.8208955223880596입니다.
770번의 평균 평점은 2.935441370223979입니다.
771번의 평균 평점은 3.769230769230769입니다.
772번의 평균 평점은 3.479591836734694입니다.
773번의 평균 평점은 3.5918367346938775입니다.
774번의 평균 평점은 3.2142857142857144입니다.
775번의 평균 평점은 4.0입니다.
776번의 평균 평점은 3.766990291262136입니다.
777번의 평균 평점은 2.5796812749003983입니다.
778번의 평균 평점은 3.785276073619632입니다.
779번의 평균 평점은 3.3333333333333335입니다.
780번의 평균 평점은 3.45703125입니다.
781번의 평균 평점은 3.1709401709401708입니다.
782번의 평균 평점은 3.4347826086956523입니다.
783번의 평균 평점은 3.5210084033613445입니다.
784번의 

1014번의 평균 평점은 3.4871794871794872입니다.
1015번의 평균 평점은 3.7262830482115086입니다.
1016번의 평균 평점은 3.7880794701986753입니다.
1017번의 평균 평점은 3.251439539347409입니다.
1018번의 평균 평점은 4.155737704918033입니다.
1019번의 평균 평점은 3.0107758620689653입니다.
1020번의 평균 평점은 3.9886363636363638입니다.
1021번의 평균 평점은 4.694656488549619입니다.
1022번의 평균 평점은 3.5616438356164384입니다.
1023번의 평균 평점은 4.073170731707317입니다.
1024번의 평균 평점은 3.697674418604651입니다.
1025번의 평균 평점은 3.757575757575758입니다.
1026번의 평균 평점은 4.0입니다.
1027번의 평균 평점은 3.8260869565217392입니다.
1028번의 평균 평점은 3.9672131147540983입니다.
1029번의 평균 평점은 3.1953125입니다.
1030번의 평균 평점은 3.5789473684210527입니다.
1031번의 평균 평점은 4.070967741935484입니다.
1032번의 평균 평점은 3.941747572815534입니다.
1033번의 평균 평점은 3.288659793814433입니다.
1034번의 평균 평점은 3.483679525222552입니다.
1035번의 평균 평점은 3.8241758241758244입니다.
1036번의 평균 평점은 4.32입니다.
1037번의 평균 평점은 3.5789473684210527입니다.
1038번의 평균 평점은 3.9324324324324325입니다.
1039번의 평균 평점은 2.892857142857143입니다.
1040번의 평균 평점은 4.235521235521236입니다.
1041번의 평균 평점은 4.317647058823529입니다.
1042번의 평균 평점은 2

1270번의 평균 평점은 3.0344827586206895입니다.
1271번의 평균 평점은 4.2823529411764705입니다.
1272번의 평균 평점은 3.535211267605634입니다.
1273번의 평균 평점은 3.9820359281437128입니다.
1274번의 평균 평점은 3.8494077834179357입니다.
1275번의 평균 평점은 4.466666666666667입니다.
1276번의 평균 평점은 4.1558441558441555입니다.
1277번의 평균 평점은 3.675675675675676입니다.
1278번의 평균 평점은 4.0입니다.
1279번의 평균 평점은 2.958448753462604입니다.
1280번의 평균 평점은 3.72입니다.
1281번의 평균 평점은 3.4791666666666665입니다.
1282번의 평균 평점은 4.095238095238095입니다.
1283번의 평균 평점은 3.347826086956522입니다.
1284번의 평균 평점은 3.4220907297830374입니다.
1285번의 평균 평점은 3.9064685314685317입니다.
1286번의 평균 평점은 3.5입니다.
1287번의 평균 평점은 3.9468085106382977입니다.
1288번의 평균 평점은 3.75968992248062입니다.
1289번의 평균 평점은 4.3076923076923075입니다.
1290번의 평균 평점은 4.181818181818182입니다.
1291번의 평균 평점은 3.802120141342756입니다.
1292번의 평균 평점은 3.3958333333333335입니다.
1293번의 평균 평점은 3.426470588235294입니다.
1294번의 평균 평점은 3.9272030651340994입니다.
1295번의 평균 평점은 3.575입니다.
1296번의 평균 평점은 3.8958333333333335입니다.
1297번의 평균 평점은 3.4455852156057496입니다.
1298번의 평균 평점은 3.8273615635179152

1521번의 평균 평점은 3.263888888888889입니다.
1522번의 평균 평점은 3.641025641025641입니다.
1523번의 평균 평점은 3.717391304347826입니다.
1524번의 평균 평점은 3.7351778656126484입니다.
1525번의 평균 평점은 3.6633663366336635입니다.
1526번의 평균 평점은 4.15625입니다.
1527번의 평균 평점은 3.1538461538461537입니다.
1528번의 평균 평점은 4.086956521739131입니다.
1529번의 평균 평점은 3.7666666666666666입니다.
1530번의 평균 평점은 3.8514851485148514입니다.
1531번의 평균 평점은 3.4615384615384617입니다.
1532번의 평균 평점은 4.095238095238095입니다.
1533번의 평균 평점은 3.84입니다.
1534번의 평균 평점은 3.619047619047619입니다.
1535번의 평균 평점은 3.896551724137931입니다.
1536번의 평균 평점은 4.222222222222222입니다.
1537번의 평균 평점은 3.763157894736842입니다.
1538번의 평균 평점은 3.989247311827957입니다.
1539번의 평균 평점은 4.37037037037037입니다.
1540번의 평균 평점은 3.805084745762712입니다.
1541번의 평균 평점은 4.423076923076923입니다.
1542번의 평균 평점은 3.6723549488054608입니다.
1543번의 평균 평점은 3.46242774566474입니다.
1544번의 평균 평점은 3.690909090909091입니다.
1545번의 평균 평점은 3.1013824884792625입니다.
1546번의 평균 평점은 3.754385964912281입니다.
1547번의 평균 평점은 3.9328358208955225입니다.
1548번의 평균 평점은 3.5833333333333335입니다.
1549번의 

1783번의 평균 평점은 3.5714285714285716입니다.
1784번의 평균 평점은 2.980769230769231입니다.
1785번의 평균 평점은 3.0555555555555554입니다.
1786번의 평균 평점은 4.018867924528302입니다.
1787번의 평균 평점은 3.3214285714285716입니다.
1788번의 평균 평점은 3.84375입니다.
1789번의 평균 평점은 4.172413793103448입니다.
1790번의 평균 평점은 3.8731563421828907입니다.
1791번의 평균 평점은 3.586206896551724입니다.
1792번의 평균 평점은 3.871794871794872입니다.
1793번의 평균 평점은 3.4006968641114983입니다.
1794번의 평균 평점은 2.4282560706401766입니다.
1795번의 평균 평점은 4.32입니다.
1796번의 평균 평점은 3.9886363636363638입니다.
1797번의 평균 평점은 4.177142857142857입니다.
1798번의 평균 평점은 3.5970149253731343입니다.
1799번의 평균 평점은 3.5164835164835164입니다.
1800번의 평균 평점은 3.615079365079365입니다.
1801번의 평균 평점은 3.9523809523809526입니다.
1802번의 평균 평점은 4.033175355450237입니다.
1803번의 평균 평점은 3.433098591549296입니다.
1804번의 평균 평점은 3.4051724137931036입니다.
1805번의 평균 평점은 4.086206896551724입니다.
1806번의 평균 평점은 4.233644859813084입니다.
1807번의 평균 평점은 3.6435643564356437입니다.
1808번의 평균 평점은 3.4193548387096775입니다.
1809번의 평균 평점은 3.142857142857143입니다.
1810번의 평균 평점은 3.775입니다.
1811번의 평균 평점은 

2036번의 평균 평점은 3.9384615384615387입니다.
2037번의 평균 평점은 3.45입니다.
2038번의 평균 평점은 3.8204545454545453입니다.
2039번의 평균 평점은 3.5785123966942147입니다.
2040번의 평균 평점은 3.369565217391304입니다.
2041번의 평균 평점은 3.5485611510791366입니다.
2042번의 평균 평점은 3.1358490566037736입니다.
2043번의 평균 평점은 2.5714285714285716입니다.
2044번의 평균 평점은 4.12입니다.
2045번의 평균 평점은 4.04입니다.
2046번의 평균 평점은 3.5903614457831323입니다.
2047번의 평균 평점은 3.588235294117647입니다.
2048번의 평균 평점은 4.142857142857143입니다.
2049번의 평균 평점은 4.114285714285714입니다.
2050번의 평균 평점은 3.896153846153846입니다.
2051번의 평균 평점은 3.432314410480349입니다.
2052번의 평균 평점은 2.9입니다.
2053번의 평균 평점은 3.4입니다.
2054번의 평균 평점은 3.408955223880597입니다.
2055번의 평균 평점은 4.173913043478261입니다.
2056번의 평균 평점은 4.09765625입니다.
2057번의 평균 평점은 3.8615384615384616입니다.
2058번의 평균 평점은 3.3191489361702127입니다.
2059번의 평균 평점은 3.549407114624506입니다.
2060번의 평균 평점은 3.1187739463601534입니다.
2061번의 평균 평점은 4.3입니다.
2062번의 평균 평점은 4.1477272727272725입니다.
2063번의 평균 평점은 2.945578231292517입니다.
2064번의 평균 평점은 4.0입니다.
2065번의 평균 평점은 4.451612903225806입니다.
2066번의 평균 평

2332번의 평균 평점은 4.065217391304348입니다.
2333번의 평균 평점은 3.7096774193548385입니다.
2334번의 평균 평점은 3.7327327327327327입니다.
2335번의 평균 평점은 3.7083333333333335입니다.
2336번의 평균 평점은 3.9523809523809526입니다.
2337번의 평균 평점은 4.181818181818182입니다.
2338번의 평균 평점은 3.8502673796791442입니다.
2339번의 평균 평점은 4.956521739130435입니다.
2340번의 평균 평점은 4.360902255639098입니다.
2341번의 평균 평점은 3.280701754385965입니다.
2342번의 평균 평점은 3.8181818181818183입니다.
2343번의 평균 평점은 4.194444444444445입니다.
2344번의 평균 평점은 3.4414893617021276입니다.
2345번의 평균 평점은 3.739130434782609입니다.
2346번의 평균 평점은 3.652173913043478입니다.
2347번의 평균 평점은 3.9130434782608696입니다.
2348번의 평균 평점은 3.150485436893204입니다.
2349번의 평균 평점은 3.1025641025641026입니다.
2350번의 평균 평점은 3.8620689655172415입니다.
2351번의 평균 평점은 3.4545454545454546입니다.
2352번의 평균 평점은 2.7142857142857144입니다.
2353번의 평균 평점은 3.6091370558375635입니다.
2354번의 평균 평점은 3.6153846153846154입니다.
2355번의 평균 평점은 3.5602836879432624입니다.
2356번의 평균 평점은 3.625입니다.
2357번의 평균 평점은 3.9310344827586206입니다.
2358번의 평균 평점은 3.857142857142857입니다.
2359번의 평균 평점은 3.62711864

2637번의 평균 평점은 3.4107142857142856입니다.
2638번의 평균 평점은 3.103646833013436입니다.
2639번의 평균 평점은 3.878787878787879입니다.
2640번의 평균 평점은 3.8095238095238093입니다.
2641번의 평균 평점은 4.09748427672956입니다.
2642번의 평균 평점은 3.915492957746479입니다.
2643번의 평균 평점은 3.398678414096916입니다.
2644번의 평균 평점은 3.857142857142857입니다.
2645번의 평균 평점은 3.400709219858156입니다.
2646번의 평균 평점은 4.130434782608695입니다.
2647번의 평균 평점은 4.333333333333333입니다.
2648번의 평균 평점은 3.94392523364486입니다.
2649번의 평균 평점은 3.1488372093023256입니다.
2650번의 평균 평점은 3.7346938775510203입니다.
2651번의 평균 평점은 3.310344827586207입니다.
2652번의 평균 평점은 4.048780487804878입니다.
2653번의 평균 평점은 3.6206896551724137입니다.
2654번의 평균 평점은 4.08입니다.
2655번의 평균 평점은 3.1315789473684212입니다.
2656번의 평균 평점은 4.090909090909091입니다.
2657번의 평균 평점은 4.045454545454546입니다.
2658번의 평균 평점은 3.903225806451613입니다.
2659번의 평균 평점은 4.105590062111801입니다.
2660번의 평균 평점은 3.6808510638297873입니다.
2661번의 평균 평점은 3.6122448979591835입니다.
2662번의 평균 평점은 3.6904761904761907입니다.
2663번의 평균 평점은 3.6858974358974357입니다.
2664번의 평균 평점은 3.449591280653951입니

2953번의 평균 평점은 3.2입니다.
2954번의 평균 평점은 3.9444444444444446입니다.
2955번의 평균 평점은 3.2408376963350785입니다.
2956번의 평균 평점은 3.4814814814814814입니다.
2957번의 평균 평점은 4.453125입니다.
2958번의 평균 평점은 3.0232558139534884입니다.
2959번의 평균 평점은 3.9726027397260273입니다.
2960번의 평균 평점은 4.032258064516129입니다.
2961번의 평균 평점은 3.977272727272727입니다.
2962번의 평균 평점은 2.8992입니다.
2963번의 평균 평점은 3.9743589743589745입니다.
2964번의 평균 평점은 4.541666666666667입니다.
2965번의 평균 평점은 3.5925925925925926입니다.
2966번의 평균 평점은 4.0625입니다.
2967번의 평균 평점은 3.455407969639469입니다.
2968번의 평균 평점은 3.788235294117647입니다.
2969번의 평균 평점은 3.7126436781609193입니다.
2970번의 평균 평점은 4.291666666666667입니다.
2971번의 평균 평점은 3.8333333333333335입니다.
2972번의 평균 평점은 3.497041420118343입니다.
2973번의 평균 평점은 3.435483870967742입니다.
2974번의 평균 평점은 4.290322580645161입니다.
2975번의 평균 평점은 4.19입니다.
2976번의 평균 평점은 3.6013986013986012입니다.
2977번의 평균 평점은 3.238095238095238입니다.
2978번의 평균 평점은 3.786127167630058입니다.
2979번의 평균 평점은 4.0입니다.
2980번의 평균 평점은 3.5955882352941178입니다.
2981번의 평균 평점은 4.266666666666667입니다.
2982번의 평균 평점은 3.6

3251번의 평균 평점은 4.464285714285714입니다.
3252번의 평균 평점은 2.8857142857142857입니다.
3253번의 평균 평점은 3.856287425149701입니다.
3254번의 평균 평점은 3.5217391304347827입니다.
3255번의 평균 평점은 3.6222222222222222입니다.
3256번의 평균 평점은 4.068965517241379입니다.
3257번의 평균 평점은 4.2592592592592595입니다.
3258번의 평균 평점은 3.85입니다.
3259번의 평균 평점은 4.045569620253165입니다.
3260번의 평균 평점은 3.9078947368421053입니다.
3261번의 평균 평점은 3.2430426716141003입니다.
3262번의 평균 평점은 3.3626373626373627입니다.
3263번의 평균 평점은 3.9292035398230087입니다.
3264번의 평균 평점은 2.75입니다.
3265번의 평균 평점은 2.8484251968503935입니다.
3266번의 평균 평점은 4.357615894039735입니다.
3267번의 평균 평점은 3.857142857142857입니다.
3268번의 평균 평점은 3.8656716417910446입니다.
3269번의 평균 평점은 3.855421686746988입니다.
3270번의 평균 평점은 3.6639344262295084입니다.
3271번의 평균 평점은 3.8214285714285716입니다.
3272번의 평균 평점은 3.77511961722488입니다.
3273번의 평균 평점은 4.1입니다.
3274번의 평균 평점은 3.242424242424242입니다.
3275번의 평균 평점은 3.4761904761904763입니다.
3276번의 평균 평점은 3.0689655172413794입니다.
3277번의 평균 평점은 4.053333333333334입니다.
3278번의 평균 평점은 3.869565217391304입니다.
3279번의 평균 평점은 2.685

3544번의 평균 평점은 4.344827586206897입니다.
3545번의 평균 평점은 3.4285714285714284입니다.
3546번의 평균 평점은 3.392682926829268입니다.
3547번의 평균 평점은 3.5359116022099446입니다.
3548번의 평균 평점은 2.5384615384615383입니다.
3549번의 평균 평점은 3.945945945945946입니다.
3550번의 평균 평점은 3.5126050420168067입니다.
3551번의 평균 평점은 3.9310344827586206입니다.
3552번의 평균 평점은 3.2입니다.
3553번의 평균 평점은 4.085106382978723입니다.
3554번의 평균 평점은 3.696969696969697입니다.
3555번의 평균 평점은 3.108527131782946입니다.
3556번의 평균 평점은 3.8660714285714284입니다.
3557번의 평균 평점은 3.864795918367347입니다.
3558번의 평균 평점은 4.31입니다.
3559번의 평균 평점은 4.391891891891892입니다.
3560번의 평균 평점은 4.45985401459854입니다.
3561번의 평균 평점은 3.976833976833977입니다.
3562번의 평균 평점은 3.38506588579795입니다.
3563번의 평균 평점은 3.843601895734597입니다.
3564번의 평균 평점은 3.25입니다.
3565번의 평균 평점은 3.1714285714285713입니다.
3566번의 평균 평점은 3.838709677419355입니다.
3567번의 평균 평점은 3.9565217391304346입니다.
3568번의 평균 평점은 3.9411764705882355입니다.
3569번의 평균 평점은 2.9016018306636155입니다.
3570번의 평균 평점은 3.1818181818181817입니다.
3571번의 평균 평점은 3.3653846153846154입니다.
3572번의 평균 평점은 4.234234

3834번의 평균 평점은 4.254448398576512입니다.
3835번의 평균 평점은 4.472527472527473입니다.
3836번의 평균 평점은 3.388235294117647입니다.
3837번의 평균 평점은 3.770408163265306입니다.
3838번의 평균 평점은 3.25입니다.
3839번의 평균 평점은 3.340909090909091입니다.
3840번의 평균 평점은 4.088235294117647입니다.
3841번의 평균 평점은 3.3445723684210527입니다.
3842번의 평균 평점은 3.687593423019432입니다.
3843번의 평균 평점은 2.6666666666666665입니다.
3844번의 평균 평점은 4.082089552238806입니다.
3845번의 평균 평점은 4.121621621621622입니다.
3846번의 평균 평점은 3.9571428571428573입니다.
3847번의 평균 평점은 2.727272727272727입니다.
3848번의 평균 평점은 4.153846153846154입니다.
3849번의 평균 평점은 3.1492537313432836입니다.
3850번의 평균 평점은 3.8671875입니다.
3851번의 평균 평점은 3.116279069767442입니다.
3852번의 평균 평점은 4.43859649122807입니다.
3853번의 평균 평점은 4.248407643312102입니다.
3854번의 평균 평점은 4.048780487804878입니다.
3855번의 평균 평점은 3.712871287128713입니다.
3856번의 평균 평점은 3.9361702127659575입니다.
3857번의 평균 평점은 3.925925925925926입니다.
3858번의 평균 평점은 4.277777777777778입니다.
3859번의 평균 평점은 3.414239482200647입니다.
3860번의 평균 평점은 3.6491228070175437입니다.
3861번의 평균 평점은 3.975609756097561입니다.
3862번의 평

4133번의 평균 평점은 3.1186440677966103입니다.
4134번의 평균 평점은 3.610169491525424입니다.
4135번의 평균 평점은 4.242424242424242입니다.
4136번의 평균 평점은 4.512820512820513입니다.
4137번의 평균 평점은 3.9176470588235293입니다.
4138번의 평균 평점은 3.96875입니다.
4139번의 평균 평점은 3.735042735042735입니다.
4140번의 평균 평점은 3.1578231292517005입니다.
4141번의 평균 평점은 3.853982300884956입니다.
4142번의 평균 평점은 3.0416666666666665입니다.
4143번의 평균 평점은 4.458333333333333입니다.
4144번의 평균 평점은 3.3214285714285716입니다.
4145번의 평균 평점은 4.12입니다.
4146번의 평균 평점은 4.12입니다.
4147번의 평균 평점은 4.327868852459017입니다.
4148번의 평균 평점은 3.8297872340425534입니다.
4149번의 평균 평점은 3.9615384615384617입니다.
4150번의 평균 평점은 3.3200992555831266입니다.
4151번의 평균 평점은 3.6666666666666665입니다.
4152번의 평균 평점은 3.670886075949367입니다.
4153번의 평균 평점은 3.7159763313609466입니다.
4154번의 평균 평점은 4.434782608695652입니다.
4155번의 평균 평점은 3.596774193548387입니다.
4156번의 평균 평점은 3.7806122448979593입니다.
4157번의 평균 평점은 3.3392857142857144입니다.
4158번의 평균 평점은 3.782608695652174입니다.
4159번의 평균 평점은 4.045454545454546입니다.
4160번의 평균 평점은 3.2583333333333333입니다.
4161번의 평균 평점은 2

4368번의 평균 평점은 3.6946564885496183입니다.
4369번의 평균 평점은 3.727272727272727입니다.
4370번의 평균 평점은 3.6666666666666665입니다.
4371번의 평균 평점은 3.6099290780141846입니다.
4372번의 평균 평점은 4.04입니다.
4373번의 평균 평점은 4.092409240924092입니다.
4374번의 평균 평점은 4.338582677165355입니다.
4375번의 평균 평점은 4.055384615384615입니다.
4376번의 평균 평점은 3.810344827586207입니다.
4377번의 평균 평점은 3.6363636363636362입니다.
4378번의 평균 평점은 3.153225806451613입니다.
4379번의 평균 평점은 3.0989583333333335입니다.
4380번의 평균 평점은 3.6556291390728477입니다.
4381번의 평균 평점은 3.4243792325056432입니다.
4382번의 평균 평점은 2.8846153846153846입니다.
4383번의 평균 평점은 3.4입니다.
4384번의 평균 평점은 4.003448275862069입니다.
4385번의 평균 평점은 3.259259259259259입니다.
4386번의 평균 평점은 3.597938144329897입니다.
4387번의 평균 평점은 3.0969044414535665입니다.
4388번의 평균 평점은 3.814814814814815입니다.
4389번의 평균 평점은 3.296입니다.
4390번의 평균 평점은 3.0863309352517985입니다.
4391번의 평균 평점은 3.675675675675676입니다.
4392번의 평균 평점은 3.44입니다.
4393번의 평균 평점은 3.9입니다.
4394번의 평균 평점은 3.515151515151515입니다.
4395번의 평균 평점은 3.3333333333333335입니다.
4396번의 평균 평점은 3.68입니다.
4397번의 평균 평점은 3.43283582

4617번의 평균 평점은 3.164383561643836입니다.
4618번의 평균 평점은 3.539473684210526입니다.
4619번의 평균 평점은 3.4444444444444446입니다.
4620번의 평균 평점은 3.8181818181818183입니다.
4621번의 평균 평점은 3.455026455026455입니다.
4622번의 평균 평점은 3.5217391304347827입니다.
4623번의 평균 평점은 3.973684210526316입니다.
4624번의 평균 평점은 3.9508196721311477입니다.
4625번의 평균 평점은 3.419753086419753입니다.
4626번의 평균 평점은 3.562176165803109입니다.
4627번의 평균 평점은 3.8932038834951457입니다.
4628번의 평균 평점은 3.6입니다.
4629번의 평균 평점은 3.375입니다.
4630번의 평균 평점은 3.793103448275862입니다.
4631번의 평균 평점은 3.604651162790698입니다.
4632번의 평균 평점은 3.9107142857142856입니다.
4633번의 평균 평점은 3.9753086419753085입니다.
4634번의 평균 평점은 4.813725490196078입니다.
4635번의 평균 평점은 3.754777070063694입니다.
4636번의 평균 평점은 2.0입니다.
4637번의 평균 평점은 3.5846560846560847입니다.
4638번의 평균 평점은 2.891891891891892입니다.
4639번의 평균 평점은 4.288461538461538입니다.
4640번의 평균 평점은 2.6578947368421053입니다.
4641번의 평균 평점은 4.025입니다.
4642번의 평균 평점은 3.696969696969697입니다.
4643번의 평균 평점은 3.0398009950248754입니다.
4644번의 평균 평점은 3.4335664335664338입니다.
4645번의 평균 평점은 4.174603174603175입니

4871번의 평균 평점은 4.0입니다.
4872번의 평균 평점은 3.5365853658536586입니다.
4873번의 평균 평점은 4.214285714285714입니다.
4874번의 평균 평점은 4.387096774193548입니다.
4875번의 평균 평점은 3.93입니다.
4876번의 평균 평점은 4.055555555555555입니다.
4877번의 평균 평점은 3.7157894736842105입니다.
4878번의 평균 평점은 3.604651162790698입니다.
4879번의 평균 평점은 3.45610278372591입니다.
4880번의 평균 평점은 3.761904761904762입니다.
4881번의 평균 평점은 3.9545454545454546입니다.
4882번의 평균 평점은 4.029556650246305입니다.
4883번의 평균 평점은 2.84입니다.
4884번의 평균 평점은 3.884020618556701입니다.
4885번의 평균 평점은 4.466666666666667입니다.
4886번의 평균 평점은 3.9901960784313726입니다.
4887번의 평균 평점은 3.392857142857143입니다.
4888번의 평균 평점은 4.344481605351171입니다.
4889번의 평균 평점은 4.347328244274809입니다.
4890번의 평균 평점은 3.4210526315789473입니다.
4891번의 평균 평점은 3.7857142857142856입니다.
4892번의 평균 평점은 3.175입니다.
4893번의 평균 평점은 3.933333333333333입니다.
4894번의 평균 평점은 3.902439024390244입니다.
4895번의 평균 평점은 4.132352941176471입니다.
4896번의 평균 평점은 3.073170731707317입니다.
4897번의 평균 평점은 3.35입니다.
4898번의 평균 평점은 4.167364016736402입니다.
4899번의 평균 평점은 3.6653061224489796입니다.
4900번의 평균 평점은 4

5128번의 평균 평점은 3.863157894736842입니다.
5129번의 평균 평점은 3.790909090909091입니다.
5130번의 평균 평점은 4.392857142857143입니다.
5131번의 평균 평점은 3.4035532994923856입니다.
5132번의 평균 평점은 4.344827586206897입니다.
5133번의 평균 평점은 3.076923076923077입니다.
5134번의 평균 평점은 3.7157894736842105입니다.
5135번의 평균 평점은 3.8701298701298703입니다.
5136번의 평균 평점은 3.7476635514018692입니다.
5137번의 평균 평점은 4.129310344827586입니다.
5138번의 평균 평점은 3.253086419753086입니다.
5139번의 평균 평점은 3.5317460317460316입니다.
5140번의 평균 평점은 3.3994638069705094입니다.
5141번의 평균 평점은 3.9767441860465116입니다.
5142번의 평균 평점은 3.5749235474006116입니다.
5143번의 평균 평점은 4.016806722689076입니다.
5144번의 평균 평점은 3.8125입니다.
5145번의 평균 평점은 3.25입니다.
5146번의 평균 평점은 3.3666666666666667입니다.
5147번의 평균 평점은 3.5945945945945947입니다.
5148번의 평균 평점은 3.8737864077669903입니다.
5149번의 평균 평점은 4.033333333333333입니다.
5150번의 평균 평점은 3.6944444444444446입니다.
5151번의 평균 평점은 2.779874213836478입니다.
5152번의 평균 평점은 3.074074074074074입니다.
5153번의 평균 평점은 3.243478260869565입니다.
5154번의 평균 평점은 4.212121212121212입니다.
5155번의 평균 평점은 2.8846153846153846입니다.
515

5369번의 평균 평점은 3.7224489795918365입니다.
5370번의 평균 평점은 2.6296296296296298입니다.
5371번의 평균 평점은 4.101851851851852입니다.
5372번의 평균 평점은 4.0입니다.
5373번의 평균 평점은 3.96875입니다.
5374번의 평균 평점은 3.6875입니다.
5375번의 평균 평점은 4.482758620689655입니다.
5376번의 평균 평점은 3.74609375입니다.
5377번의 평균 평점은 3.697674418604651입니다.
5378번의 평균 평점은 3.6685082872928176입니다.
5379번의 평균 평점은 3.810810810810811입니다.
5380번의 평균 평점은 3.05입니다.
5381번의 평균 평점은 4.0입니다.
5382번의 평균 평점은 3.925373134328358입니다.
5383번의 평균 평점은 4.0입니다.
5384번의 평균 평점은 4.413043478260869입니다.
5385번의 평균 평점은 4.0입니다.
5386번의 평균 평점은 3.813664596273292입니다.
5387번의 평균 평점은 3.5471956224350207입니다.
5388번의 평균 평점은 3.9583333333333335입니다.
5389번의 평균 평점은 3.357142857142857입니다.
5390번의 평균 평점은 3.863013698630137입니다.
5391번의 평균 평점은 3.4347826086956523입니다.
5392번의 평균 평점은 4.136363636363637입니다.
5393번의 평균 평점은 3.1857142857142855입니다.
5394번의 평균 평점은 3.3616018845700824입니다.
5395번의 평균 평점은 3.6942148760330578입니다.
5396번의 평균 평점은 4.1234567901234565입니다.
5397번의 평균 평점은 3.2989690721649483입니다.
5398번의 평균 평점은 4.035714285714286입니다.
5399번의

5680번의 평균 평점은 4.044025157232705입니다.
5681번의 평균 평점은 3.6363636363636362입니다.
5682번의 평균 평점은 3.7335526315789473입니다.
5683번의 평균 평점은 3.7295081967213113입니다.
5684번의 평균 평점은 3.4376278118609407입니다.
5685번의 평균 평점은 3.6입니다.
5686번의 평균 평점은 2.0452830188679245입니다.
5687번의 평균 평점은 3.6941176470588237입니다.
5688번의 평균 평점은 3.46입니다.
5689번의 평균 평점은 3.627049180327869입니다.
5690번의 평균 평점은 4.458333333333333입니다.
5691번의 평균 평점은 4.1461538461538465입니다.
5692번의 평균 평점은 4.0입니다.
5693번의 평균 평점은 3.4782608695652173입니다.
5694번의 평균 평점은 4.2입니다.
5695번의 평균 평점은 3.225806451612903입니다.
5696번의 평균 평점은 4.5입니다.
5697번의 평균 평점은 3.6538461538461537입니다.
5698번의 평균 평점은 3.6285714285714286입니다.
5699번의 평균 평점은 3.137123745819398입니다.
5700번의 평균 평점은 3.9473684210526314입니다.
5701번의 평균 평점은 3.8739495798319328입니다.
5702번의 평균 평점은 3.8632478632478633입니다.
5703번의 평균 평점은 3.9594594594594597입니다.
5704번의 평균 평점은 4.258064516129032입니다.
5705번의 평균 평점은 3.699421965317919입니다.
5706번의 평균 평점은 3.860606060606061입니다.
5707번의 평균 평점은 4.26입니다.
5708번의 평균 평점은 3.1입니다.
5709번의 평균 평점은 3.7580645161290325입니다.
5

5980번의 평균 평점은 3.6320754716981134입니다.
5981번의 평균 평점은 3.617857142857143입니다.
5982번의 평균 평점은 3.9291338582677167입니다.
5983번의 평균 평점은 4.107142857142857입니다.
5984번의 평균 평점은 4.7입니다.
5985번의 평균 평점은 3.727272727272727입니다.
5986번의 평균 평점은 4.441666666666666입니다.
5987번의 평균 평점은 3.389830508474576입니다.
5988번의 평균 평점은 3.2278481012658227입니다.
5989번의 평균 평점은 3.9740259740259742입니다.
5990번의 평균 평점은 3.444055944055944입니다.
5991번의 평균 평점은 3.588235294117647입니다.
5992번의 평균 평점은 3.4776119402985075입니다.
5993번의 평균 평점은 3.566666666666667입니다.
5994번의 평균 평점은 4.32051282051282입니다.
5995번의 평균 평점은 3.956989247311828입니다.
5996번의 평균 평점은 3.8104906937394247입니다.
5997번의 평균 평점은 4.4035087719298245입니다.
5998번의 평균 평점은 3.2721518987341773입니다.
5999번의 평균 평점은 4.111111111111111입니다.
6000번의 평균 평점은 3.2450592885375493입니다.
6001번의 평균 평점은 3.594017094017094입니다.
6002번의 평균 평점은 4.071641791044776입니다.
6003번의 평균 평점은 4.106299212598425입니다.
6004번의 평균 평점은 3.3859649122807016입니다.
6005번의 평균 평점은 3.6704545454545454입니다.
6006번의 평균 평점은 3.161290322580645입니다.
6007번의 평균 평점은 3.1533742331288344